site_name: CyberCloud Guru
site_url: https://cybercloud.guru/
site_description: Easy to follow and understand tutorials with real-world examples for Application Security, CloudSecurity, DevSecOps, AI security and many more.
site_author: Sanjeev Jaiswal (Jassi)
copyright: '&copy; Copyright 2026 - Developed with Care by CyberCloud Gurus'

theme:
  name: material #mkdocs, readthedocs, material
  nav_style: dark
  logo: "assets/images/logo.png"
  favicon: "assets/images/favicon.png"
  analytics:
    gtag: G-6SNSTEDE6T
  features:
    - navigation.top
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.indexes
    - navigation.tracking
    - search.suggest
    - search.highlight
    - content.tooltips
  icon:
    repo: fontawesome/brands/github
  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: light blue
      accent: blue grey
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: light blue
      accent: light blue
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

plugins:
  - search
  - minify:
      minify_html: true
      minify_js: true
      minify_css: true
      htmlmin_opts:
          remove_comments: true

nav:
    - Home: 
      - 'Site Overview': index.md
      - 'Cybersecurity Overview': cybersecurity-overview.md
      - 'Common Security Concepts': common-security-concepts.md
    - Product Security:
      - 'Product Security Overview': product-security/index.md
      - Web Security:
          - 'Web Security Overview': product-security/web-security/web-security-overview.md
          - 'OWASP Top 10 2021': product-security/web-security/owasp-top10.md
          - 'Web Security Concepts': product-security/web-security/web-security-concepts.md
      - Network Security: 
          - 'Network Security Overview': product-security/network-security/network-security-overview.md
      - Application Security:
          - 'Secure Coding': product-security/application-security/secure-coding.md
          - 'Secure Code Review': product-security/application-security/secure-code-review.md
          - 'Cryptography': product-security/application-security/cryptography.md
          - 'Threat Modeling': product-security/application-security/threat-modeling.md
          - 'API Security': product-security/application-security/api-security.md
          - 'SAST': product-security/application-security/sast.md
          - 'SCA': product-security/application-security/sca.md
      - Cloud Security:
        - 'Cloud Security Essentials': product-security/cloud-security/cloud-security-essentials.md
        - 'OWASP Top 10 Cloud': product-security/cloud-security/owasp-top10-cloud.md
        - 'Learning AWS Security':
          - 'AWS Security Overview': product-security/cloud-security/learning-aws-security/aws-security-overview.md
          - 'IAM Security': product-security/cloud-security/learning-aws-security/iam-security.md
          - 'S3 Security': product-security/cloud-security/learning-aws-security/s3-security.md
          - 'Cloudtrail': product-security/cloud-security/learning-aws-security/cloudtrail.md
          - 'GuardDuty': product-security/cloud-security/learning-aws-security/guardduty.md
          - 'KMS': product-security/cloud-security/learning-aws-security/kms.md
        - 'Learning GCP Security':
          - 'GCP Security Overview': product-security/cloud-security/learning-gcp-security/gcp-security-overview.md
        - 'Learning Azure Security':
          - 'Azure Security Overview': product-security/cloud-security/learning-azure-security/azure-security-overview.md
      - Container Security:
        - 'Container Overview': product-security/container-security/container-overview.md
        - 'Introduction to Docker': product-security/container-security/docker-introduction.md
        - 'Docker Security': product-security/container-security/docker-security.md
        - 'Kubernetes': product-security/container-security/kubernetes.md
        - 'Kubernetes Security': product-security/container-security/kubernetes-security.md  
      - DevSecOps:
        - 'DevSecOps Fundamentals': product-security/devsecops/devsecops-fundamentals.md
        - 'DevSecOps Maturity Model': product-security/devsecops/devsecops-maturity.md
        - 'Ansible': product-security/devsecops/ansible.md
        - 'Terraform': product-security/devsecops/terraform.md
        - 'Pulumi': product-security/devsecops/pulumi.md
        - 'Jenkins': product-security/devsecops/jenkins.md
        - 'SDL in CI/CD Pipeline': product-security/devsecops/sdl-cicd.md
        - 'SCA in CI/CD Pipeline': product-security/devsecops/sca-cicd.md
        - 'DAST in CI/CD Pipeline': product-security/devsecops/dast-cicd.md
        - 'Compliance as a Code': product-security/devsecops/compliance-as-code.md
        - 'Automated Vulnerability Management': product-security/devsecops/vulnerability-management.md
    - AI Security:
      - 'AI Security Overview': ai-security/ai-security-overview.md
      - 'AI Security Fundamentals': ai-security/ai-security-fundamentals.md
      - 'AI Threat Modeling': ai-security/ai-threat-modeling.md
      - 'AI Data Security': ai-security/ai-data-security.md
      - 'AI Model Security': ai-security/ai-model-security.md
      - 'AI Governance': ai-security/ai-governance.md
    - GRC:
      - 'GRC Overview': grc/grc-overview.md
      - 'ISO/IEC 27001:2022': grc/iso27k1.md
      - 'Data Privacy': grc/data-privacy.md
      - 'GDPR': grc/gdpr.md
      - 'NIST RMF': grc/nist-rmf.md
      - 'NIST CSF': grc/nist-csf.md
    - Python Track:
        - 'Python Track Introduction': python-track/python-track-overview.md
        - 'Learning Python': python-track/learning-python.md
        - 'Python for AWS': python-track/python-for-aws.md
        - 'Python for Automation': python-track/python-for-automation.md
        - 'Python for DevOps': python-track/python-for-devops.md
        - 'Python for Cybersecurity': python-track/python-for-cybersecurity.md
    - Study Plan:
        - 'All Study Plans': study-plan/index.md
    - Miscellaneous:
      - 'Linux Commands': miscellaneous/linux-commands.md
      - 'ViM for Everyone': miscellaneous/vim-essentials.md
      - 'Regular Expression Essentials': miscellaneous/regular-expression.md
      - 'Git Essentials with Examples': miscellaneous/git-basics.md
    - Slides:
      - 'Slides Lists': slides/index.md
      - Common Cybersecurity Presentations:
        - 'Cybersecurity Roadmap for Beginners': slides/security-presentations/common-security/cybersecurity-roadmap-for-beginners.md
        - 'Social Engineering Basics': slides/security-presentations/common-security/social-engineering-basics.md
        - 'How to Build a Career in Cybersecurity': slides/security-presentations/common-security/how-to-build-a-career-in-cybersecurity.md
      - Application Security:
        - 'Threat Modeling Hands-On': slides/security-presentations/application-security/threat-modeling-handson.md
        - 'API Security 101': slides/security-presentations/application-security/api-security-101.md
        - 'OWASP Top 10 for API': slides/security-presentations/application-security/owasp-top10-api.md
        - 'OWASP Top 10 for web': slides/security-presentations/web-security/owasp-top10-web.md
        - 'Web Security 101': slides/security-presentations/web-security/web-security-101.md
      - Cloud Security:
        - 'Cloud Security 101': slides/security-presentations/cloud-security/cloud-security-101.md
        - 'Penetration Testing AWS': slides/security-presentations/cloud-security/penetration-testing-aws.md
      - Python Track:
          - 'Python for AWS': slides/python-track/python-for-aws.md
          - 'Python for Web Security': slides/python-track/python-for-web-security.md

extra:
  consent:
    title: Cookie consent
    description: >-
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/jassics
      name: follow Sanjeev Jaiswal
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/jassics
      name: follow Sanjeev Jaiswal
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/jassics
      name: connect Sanjeev on Linkedin
  generator: false

# Strategy: Use an absolute path
markdown_extensions:
  - pymdownx.pathconverter:
      base_path: 'jassics/CybercloudLearning' # default: ''
      relative_path: '' # default ''
      absolute: false # default: false
      tags: 'a script img link object embed'
  - admonition
  - pymdownx.details
  - pymdownx.superfences
