site_name: CyberCloud Guru
site_url: https://cybercloud.guru/
site_description: Tutorials for Cybersecurity, CloudSecurity, DevSecOps and many more with an easy to understand examples.
site_author: Sanjeev Jaiswal (Jassi)
copyright: '&copy; Copyright 2023 - Developed with Care by CyberCloud Gurus'
repo_url: https://github.com/jassics/CybercloudLearning
repo_name: jassics/CybercloudLearning
edit_uri: blob/main/docs/

theme:
  name: material #mkdocs, readthedocs, material
  nav_style: dark
  logo: "assets/images/logo.png"
  favicon: "assets/images/favicon.png"
  analytics:
    gtag: G-6SNSTEDE6T
  features:
    - navigation.top
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.indexes
    - navigation.tracking
    - search.suggest
    - search.highlight
    - content.tooltips
  icon:
    repo: fontawesome/brands/github
  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: light blue
      accent: blue grey
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: light blue
      accent: light blue
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

plugins:
  - search
  - minify:
      minify_html: true
      minify_js: true
      minify_css: true
      htmlmin_opts:
          remove_comments: true

nav:
    - Home: index.md
    - Cloud Computing:
      - 'Cloud Computing Essentials': cloud-computing/cloud-basics.md
      - 'Learning AWS':
        - 'AWS Overview': cloud-computing/learning-aws/index.md
        - 'Compute':
          - 'Compute Overview': cloud-computing/learning-aws/compute/index.md
          - 'Amazon EC2': cloud-computing/learning-aws/compute/amazon-ec2.md
          - 'AWS Lambda': cloud-computing/learning-aws/compute/aws-lambda.md
          - 'Amazon Lightsail': cloud-computing/learning-aws/compute/amazon-lightsail.md
          - 'AWS Auto Scaling': cloud-computing/learning-aws/compute/aws-auto-scaling.md
          - 'AWS Elastic Beanstalk': cloud-computing/learning-aws/compute/aws-elastic-beanstalk.md
        - 'Containers':
          - 'Containers Overview': cloud-computing/learning-aws/containers/index.md
          - 'Amazon ECR': cloud-computing/learning-aws/containers/amazon-ecr.md
          - 'Amazon ECS': cloud-computing/learning-aws/containers/amazon-ecs.md
          - 'Amazon EKS': cloud-computing/learning-aws/containers/amazon-eks.md
          - 'AWS Fargate': cloud-computing/learning-aws/containers/aws-fargate.md
        - 'Database':
          - 'Database Overview': cloud-computing/learning-aws/database/index.md
          - 'Amazon Aurora': cloud-computing/learning-aws/database/amazon-aurora.md
          - 'Amazon DynamoDB': cloud-computing/learning-aws/database/amazon-dynamodb.md
          - 'Amazon Elasticache': cloud-computing/learning-aws/database/amazon-elasticache.md
          - 'Amazon Neptune': cloud-computing/learning-aws/database/amazon-neptune.md
          - 'Amazon RDS': cloud-computing/learning-aws/database/amazon-rds.md
          - 'Amazon Redshift': cloud-computing/learning-aws/database/amazon-redshift.md
        - 'Management and Governance':
          - 'Management and Governance Overview': cloud-computing/learning-aws/management-and-governance/index.md
          - 'Amazon CloudWatch': cloud-computing/learning-aws/management-and-governance/amazon-cloudwatch.md
          - 'AWS CloudTrail': cloud-computing/learning-aws/management-and-governance/aws-cloudtrail.md
          - 'AWS Config': cloud-computing/learning-aws/management-and-governance/aws-config.md
          - 'AWS Organizations': cloud-computing/learning-aws/management-and-governance/aws-organizations.md
          - 'AWS Trusted Advisor': cloud-computing/learning-aws/management-and-governance/aws-trusted-advisor.md
        - 'Networking':
          - 'Networking Overview': cloud-computing/learning-aws/networking/index.md
          - 'Amazon VPC': cloud-computing/learning-aws/networking/amazon-vpc.md
          - 'Amazon API Gateway': cloud-computing/learning-aws/networking/amazon-api-gateway.md
          - 'Amazon CloudFront': cloud-computing/learning-aws/networking/amazon-cloudfront.md
          - 'Amazon Route53': cloud-computing/learning-aws/networking/amazon-route53.md
          - 'Elastic Load Balancing': cloud-computing/learning-aws/networking/elb.md
        - 'Security, Identity and Compliance':
          - 'Security, Identity and Compliance Overview': cloud-computing/learning-aws/security-identity-compliance/index.md
          - 'AWS IAM': cloud-computing/learning-aws/security-identity-compliance/aws-iam.md
          - 'Amazon Cognito': cloud-computing/learning-aws/security-identity-compliance/amazon-cognito.md
          - 'Amazon Detective': cloud-computing/learning-aws/security-identity-compliance/amazon-detective.md
          - 'Amazon GuardDuty': cloud-computing/learning-aws/security-identity-compliance/amazon-guardduty.md
          - 'Amazon Inspector': cloud-computing/learning-aws/security-identity-compliance/amazon-inspector.md
          - 'Amazon Macie': cloud-computing/learning-aws/security-identity-compliance/amazon-macie.md
          - 'AWS KMS': cloud-computing/learning-aws/security-identity-compliance/aws-kms.md
          - 'AWS Secrets Manager': cloud-computing/learning-aws/security-identity-compliance/aws-secrets-manager.md
          - 'AWS Security Hub': cloud-computing/learning-aws/security-identity-compliance/aws-security-hub.md
        - 'Storage':
          - 'Storage Overview': cloud-computing/learning-aws/storage/index.md
          - 'Amazon S3': cloud-computing/learning-aws/storage/amazon-s3.md
          - 'Amazon EBS': cloud-computing/learning-aws/storage/amazon-ebs.md
          - 'Amazon EFS': cloud-computing/learning-aws/storage/amazon-efs.md
        - 'Application Integration':
          - 'Application Integration Overview': cloud-computing/learning-aws/application-integration/index.md
          - 'Amazon EventBridge': cloud-computing/learning-aws/application-integration/amazon-eventbridge.md
          - 'Amazon SNS': cloud-computing/learning-aws/application-integration/amazon-sns.md
          - 'Amazon SQS': cloud-computing/learning-aws/application-integration/amazon-sqs.md
          - 'AWS Step Functions': cloud-computing/learning-aws/application-integration/aws-step-functions.md
        - 'Analytics':
          - 'Analytics Overview': cloud-computing/learning-aws/analytics/index.md
          - 'Amazon Athena': cloud-computing/learning-aws/analytics/amazon-athena.md
          - 'Amazon Kinesis': cloud-computing/learning-aws/analytics/amazon-kinesis.md
          - 'Amazon Redshift': cloud-computing/learning-aws/analytics/amazon-redshift.md
          - 'AWS Glue': cloud-computing/learning-aws/analytics/aws-glue.md
      - 'Learning GCP':
        - 'GCP Overview': cloud-computing/learning-gcp/index.md
      - 'Learning Azure':
            - 'Azure Overview': cloud-computing/learning-azure/index.md
    - Cloud Security:
      - 'Cloud Security Essentials': cloud-security/cloud-security-essentials.md
      - 'OWASP Top 10 Cloud': cloud-security/owasp-top10-cloud.md
      - 'Learning AWS Security':
        - 'AWS Security Overview': cloud-security/learning-aws-security/aws-security-overview.md
        - 'IAM Security': cloud-security/learning-aws-security/iam-security.md
        - 'S3 Security': cloud-security/learning-aws-security/s3-security.md
        - 'Cloudtrail': cloud-security/learning-aws-security/cloudtrail.md
        - 'GuardDuty': cloud-security/learning-aws-security/guardduty.md
        - 'KMS': cloud-security/learning-aws-security/kms.md
      - 'Learning GCP Security':
        - 'GCP Security Overview': cloud-security/learning-gcp-security/gcp-security-overview.md
      - 'Learning Azure Security':
        - 'Azure Security Overview': cloud-security/learning-azure-security/azure-security-overview.md
    - Containers:
        - 'Container Overview': containers/container-overview.md
        - 'Docker':
          - 'Introduction to Docker': containers/docker/docker-introduction.md
        - 'Docker Security': containers/docker-security.md
        - 'Kubernetes': containers/kubernetes.md
        - 'Kubernetes Security': containers/kubernetes-security.md
    - Cybersecurity:
      - 'Cybersecurity Overview': cybersecurity/cybersecurity-overview.md
      - 'Common Security Concepts': cybersecurity/common-security-concepts.md
      - 'Web Security':
        - 'Web Security Overview': cybersecurity/web-security/web-security-overview.md
        - 'OWASP Top 10 2021': cybersecurity/web-security/owasp-top10.md
        - 'Web Security Concepts': cybersecurity/web-security/web-security-concepts.md
      - 'Network Security': cybersecurity/network-security.md
      - 'API Security': cybersecurity/api-security.md
      - 'Application Security':
          - 'Secure Coding': cybersecurity/application-security/secure-coding.md
          - 'Secure Code Review': cybersecurity/application-security/secure-code-review.md
          - 'Cryptography': cybersecurity/application-security/cryptography.md
          - 'Threat Modeling': cybersecurity/application-security/threat-modeling.md
          - 'SAST': cybersecurity/application-security/sast.md
          - 'SCA': cybersecurity/application-security/sca.md
    - DevOps:
        - 'Understanding DevOps': devops/devops-introduction.md
        - 'Ansible': devops/ansible.md
        - 'Terraform': devops/terraform.md
        - 'CloudFormation': devops/cloudformation.md
        - 'Pulumi': devops/pulumi.md
    - DevSecOps:
        - 'DevSecOps Fundamentals': devsecops/devsecops-fundamentals.md
        - 'DevSecOps Maturity Model': devsecops/devsecops-maturity.md
        - 'SDL in CI/CD Pipeline': devsecops/sdl-cicd.md
        - 'SCA in CI/CD Pipeline': devsecops/sca-cicd.md
        - 'DAST in CI/CD Pipeline': devsecops/dast-cicd.md
        - 'Compliance as a Code': devsecops/compliance-as-code.md
        - 'Automated Vulnerability Management': devsecops/vulnerability-management.md
    - GRC:
      - 'GRC Overview': grc/grc-overview.md
      - 'ISO/IEC 27001:2022': grc/iso27k1.md
      - 'Data Privacy': grc/data-privacy.md
      - 'GDPR': grc/gdpr.md
      - 'NIST RMF': grc/nist-rmf.md
      - 'NIST CSF': grc/nist-csf.md
    - Python Track:
        - 'Python Track Introduction': python-track/python-track-overview.md
        - 'Learning Python': python-track/learning-python.md
        - 'Python for AWS': python-track/python-for-aws.md
        - 'Python for Automation': python-track/python-for-automation.md
        - 'Python for DevOps': python-track/python-for-devops.md
        - 'Python for Cybersecurity': python-track/python-for-cybersecurity.md
    - Study Plan:
        - 'Study Plans': study-plan/index.md
        - 'Common Skills required for security study plan': study-plan/common-skills-study-plan.md
        - Cybersecurity:
          - 'Application Security Study Plan': study-plan/cybersecurity/application-security-study-plan.md
          - 'Web Security Testing Study Plan': study-plan/cybersecurity/web-security-testing-study-plan.md
          - 'Network Security Study Plan': study-plan/cybersecurity/network-security-study-plan.md
        - Cloud Security:
          - 'AWS Security Study Plan': study-plan/cloud-security/aws-security-study-plan.md
          - 'Azure Security Study Plan': study-plan/cloud-security/azure-security-study-plan.md
          - 'GCP Security Study Plan': study-plan/cloud-security/gcp-security-study-plan.md
        - 'DevSecOps Study Plan': study-plan/devsecops-study-plan.md
        - 'Docker Security Study Plan': study-plan/docker-security-study-plan.md
        - 'Kubernetes Security Study Plan': study-plan/kubernetes-security-study-plan.md
        - 'Python for Security Study Plan': study-plan/python-for-security-study-plan.md
        - DevOps:
          - 'Docker Study Plan': study-plan/devops/docker-study-plan.md
          - 'Kubernetes Study Plan': study-plan/devops/kubernetes-study-plan.md
          - 'Terraform Study Plan': study-plan/devops/terraform-study-plan.md
    - Miscellaneous:
      - 'Linux Commands': miscellaneous/linux-commands.md
      - 'ViM for Everyone': miscellaneous/vim-essentials.md
      - 'Regular Expression Essentials': miscellaneous/regular-expression.md
      - 'Git Essentials with Examples': miscellaneous/git-basics.md
    - 'Slides':
      - 'Slides Lists': slides/index.md
      - 'Common Cybersecurity Presentations':
        - 'Cybersecurity Roadmap for Beginners': slides/security-presentations/common-security/cybersecurity-roadmap-for-beginners.md
        - 'Social Engineering Basics': slides/security-presentations/common-security/social-engineering-basics.md
        - 'How to Build a Career in Cybersecurity': slides/security-presentations/common-security/how-to-build-a-career-in-cybersecurity.md
      - 'Application Security':
        - 'Threat Modeling Hands-On': slides/security-presentations/application-security/threat-modeling-handson.md
        - 'API Security 101': slides/security-presentations/application-security/api-security-101.md
        - 'OWASP Top 10 for API': slides/security-presentations/application-security/owasp-top10-api.md
        - 'OWASP Top 10 for web': slides/security-presentations/web-security/owasp-top10-web.md
        - 'Web Security 101': slides/security-presentations/web-security/web-security-101.md
      - 'Cloud Security':
        - 'Cloud Security 101': slides/security-presentations/cloud-security/cloud-security-101.md
        - 'Penetration Testing AWS': slides/security-presentations/cloud-security/penetration-testing-aws.md
      - 'Python Track':
          - 'Python for AWS': slides/python-track/python-for-aws.md
          - 'Python for Web Security': slides/python-track/python-for-web-security.md

extra:
  consent:
    title: Cookie consent
    description: >-
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/jassics
      name: follow Sanjeev Jaiswal
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/jassics
      name: follow Sanjeev Jaiswal
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/jassics
      name: connect Sanjeev on Linkedin
  generator: false

# Strategy: Use an absolute path
markdown_extensions:
  - pymdownx.pathconverter:
      base_path: 'jassics/CybercloudLearning' # default: ''
      relative_path: '' # default ''
      absolute: false # default: false
      tags: 'a script img link object embed'
  - admonition
  - pymdownx.details
  - pymdownx.superfences