name: Build and Push Cybercloud.guru

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]

    permissions:
      contents: read
      packages: write
    
    steps:
      - uses: actions/checkout@v3

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: pip install -r requirements.txt
      
      - name: Build Cybercloud using mkdocs
        run: mkdocs build

      - name: display site folder
        run: |
          ls -lrt
          ls -lRa site/
  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    permissions:
      contents: read
      packages: write

    steps:
      - name: display site folder
        run: |
          ls -lrt
          ls -lRa site/

      - name: Deploy to cybercloud.guru
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: 22
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "site/*"
          target: "/home4/alienco2/public_html/cybercloud"
      
        
