name: Build and Push Cybercloud.guru

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]

    permissions:
      contents: read
      packages: write
    
    steps:
      - uses: actions/checkout@v3

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: pip install -r requirements.txt
      
      - name: Build Cybercloud using mkdocs
        run: mkdocs build

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: site
          path: site/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    permissions:
      contents: read
      packages: write

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: site
          path: site/

      - name: Build tar
        run: |
          tar -cvf site.tar ./site

      - name: Retrieve the ssh private key and decode it to a file
        env:
          CERTIFICATE_BASE64: ${{ secrets.SSH_PRIVATE_KEY }}
          PUB_BASE64: ${{ secrets.SSH_PUBLIC_KEY }}
        run: |
          echo $CERTIFICATE_BASE64 | base64 --decode > priv_key
          mkdir -p ~/.ssh
          echo $PUB_BASE64 | base64 --decode >> ~/.ssh/known_hosts
      - name: scp to cybercloud.guru
        run: |
          chmod 400 priv_key
          scp -i priv_key -v -r site/*  ${{ vars.USERNAME }}@${{ vars.HOST }}:/home4/alienco2/public_html/cybercloud
