name: Build and Push Cybercloud.guru

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]

    permissions:
      contents: read
      packages: write
    
    steps:
      - uses: actions/checkout@v3

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: pip install -r requirements.txt
      
      - name: Build Cybercloud using mkdocs
        run: mkdocs build

  

      - name: display site folder
        run: |
          ls -lrt
          ls -lRa site/

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: site
          path: site/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    permissions:
      contents: read
      packages: write

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: site
      
      - name: display site folder
        run: |
          ls -lrt
          cd ..
          ls -lRt

      - name: installing scp
        run: |
          sudo apt-get update -y
          sudo apt-get install openssh-client -y

      - name: scp to cybercloud.guru
        run: |
          echo ${{ secrets.SSH_PRIVATE_KEY }} >> private_key
          scp -i private_key -r site/*  ${{ secrets.USERNAME }}@${{ secrets.HOST }}:/home4/alienco2/public_html/cybercloud
